#!/bin/bash

options=(
  style=round
  width=2.5
  hidpi=on
  active_color=0xffe1e3e4
  # active_color="gradient(top_left=0xffe1e3e4,bottom_right=0xff222222)"
  inactive_color=0xff494d64
  background_color=0x302c2e34
  # blur_radius=64
)

borders "${options[@]}"
