#!/bin/bash

options=(
  style=round
  width=4
  hidpi=on
  active_color=0xffb4befe
  # active_color="gradient(top_left=0xffb4befe,bottom_right=0xff222222)"
  inactive_color=0xff6c7086
  background_color=0xff1e1e2e
  # blur_radius=64
)

borders "${options[@]}"
