#!/usr/bin/env sh

#  This command is the one that loads the scripting addition.
#  Configure your user to execute `yabai --load-sa` as the root user without having to enter a password.
#  https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
#  If you have any issue with space creation or anything of that nature, you will have to reload the sa and kill the dock.
#  https://github.com/koekeishiya/yabai/issues/2151#issuecomment-1987040750

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

###############################################################################
# Layout Settings
###############################################################################

yabai -m config layout bsp

###############################################################################
# Padding Settings
###############################################################################
yabai -m config top_padding 16
yabai -m config bottom_padding 16
yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config window_gap 16

###############################################################################
# Focus & Mouse Settings
###############################################################################
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus # options: off, autoraise, autofocus
yabai -m mouse_modifier fn # set mouse interaction modifier key (options: ctrl, opt, cmd, fn)
yabai -m mouse_action1 move
yabai -m mouse_action2 resize
yabai -m mouse_drop_action swap

###############################################################################
# Window Behavior Settings
###############################################################################
yabai -m config window_zoom_persist off
yabai -m config window_placement second_child
yabai -m config window_shadow float
yabai -m split_ratio 0.50
yabai -m auto_balance on
yabai -m auto_padding on

###############################################################################
# Window Appearance Settings
###############################################################################
yabai -m window_opacity off
yabai -m window_opacity_duration 0.4
yabai -m active_window_opacity 1.0
yabai -m normal_window_opacity 0.7
yabai -m window_animation_duration 0.0
yabai -m window_animation_easing ease_in_sine
yabai -m insert_feedback_color 0xff9dd274

###############################################################################
#                              Excluded apps
###############################################################################

# System & Settings Apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Software Update$" manage=off
yabai -m rule --add app="^Time Machine$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

# Security & Productivity Apps  
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="Reminders$" manage=off
yabai -m rule --add app="^Raycast$" manage=off

# Communication & Media Apps
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^mpv$" manage=off  # Media player - better as floating window for video playback
#yabai -m rule --add app="^zoom.us$" manage=off

# Utility Apps
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^App Store$" manage=off

# Finder Special Windows
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

###############################################################################
#                              Signals
###############################################################################

# SketchyBar Events
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change &> /dev/null"