# ENVY ZSH Configuration

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
    git
    gh
    macos
    brew
    fzf-zsh-plugin
)

# ZSH Auto-Suggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# ZSH Completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export LS_COLORS="$(vivid generate catppuccin-mocha)"

# Load Aliases
for alias_file in ~/.config/aliases/*.sh; do
    [ -r "$alias_file" ] && source "$alias_file"
done

# Zoxide
eval "$(zoxide init zsh)"

# FZF
source <(fzf --zsh)

# ZSH Syntax Highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
