# ENVY ZSH Configuration

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
    git
    gh
    macos
    brew
    fzf-zsh-plugin
)

# ZSH Auto-Suggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# ZSH Completions
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export LS_COLORS="$(vivid generate catppuccin-mocha)"

# Load Aliases
for alias_file in ~/.config/aliases/*.sh; do
    [ -r "$alias_file" ] && source "$alias_file"
done

# Zoxide
eval "$(zoxide init zsh)"

# FZF
source <(fzf --zsh)

# ZSH Syntax Highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Herd PHP Binary
export PATH="/Users/raven/Library/Application Support/Herd/bin/":$PATH

# Herd PHP 8.3 Configuration
export HERD_PHP_83_INI_SCAN_DIR="/Users/raven/Library/Application Support/Herd/config/php/83/"

# Herd PHP 8.4 Configuration
export HERD_PHP_84_INI_SCAN_DIR="/Users/raven/Library/Application Support/Herd/config/php/84/"
