-- Left items (L to R)
require("items.apple")
require("items.menus")
require("items.spaces")
-- require("items.spaces_yabai_simple")
require("items.front_app")

-- Right items (R to L)
require("items.calendar")
require("items.widgets")
require("items.media")
